
// 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑
// 🛑 THIS IS AN AUTOGENERATED FILE - DO NOT EDIT DIRECTLY 🛑
// 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑

// @ts-nocheck
/* eslint-disable */
export type CoercedEnvSchema = {
  /** **APP_ENV** */
  APP_ENV: string;
  
  /** **NEXT_PUBLIC_API_BASE_URL** */
  NEXT_PUBLIC_API_BASE_URL: string;
  
  /** **NEXT_PUBLIC_CAL_COM_URL** */
  NEXT_PUBLIC_CAL_COM_URL: string;
  
  /** **NEXT_PUBLIC_SITE_URL** */
  NEXT_PUBLIC_SITE_URL: string;
  
  /** **NEXT_PUBLIC_BUSINESS_NAME** */
  NEXT_PUBLIC_BUSINESS_NAME: string;
  
  /** **NEXT_PUBLIC_LOCATION_LABEL** */
  NEXT_PUBLIC_LOCATION_LABEL: string;
  
  /** **NEXT_PUBLIC_SUPPORT_EMAIL** */
  NEXT_PUBLIC_SUPPORT_EMAIL: string;
  
  /** **NEXT_PUBLIC_PHONE_DISPLAY** */
  NEXT_PUBLIC_PHONE_DISPLAY: string;
  
  /** **NEXT_PUBLIC_MARKETING_MENU_ENABLED** */
  NEXT_PUBLIC_MARKETING_MENU_ENABLED: boolean;
  
  /** **NEXT_PUBLIC_STORAGE_BACKEND** */
  NEXT_PUBLIC_STORAGE_BACKEND: string;
  
  /** **NEXT_PUBLIC_SUPABASE_URL** */
  NEXT_PUBLIC_SUPABASE_URL?: string;
  
  /** **NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY** */
  NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY?: string;
  
};

type _CoercedEnvSchema_0ed98659 = CoercedEnvSchema;

declare module 'varlock/env' {
  export interface TypedEnvSchema extends Readonly<_CoercedEnvSchema_0ed98659> {}
  export interface PublicTypedEnvSchema extends Readonly<Pick<_CoercedEnvSchema_0ed98659, 'APP_ENV' | 'NEXT_PUBLIC_API_BASE_URL' | 'NEXT_PUBLIC_CAL_COM_URL' | 'NEXT_PUBLIC_SITE_URL' | 'NEXT_PUBLIC_BUSINESS_NAME' | 'NEXT_PUBLIC_LOCATION_LABEL' | 'NEXT_PUBLIC_SUPPORT_EMAIL' | 'NEXT_PUBLIC_PHONE_DISPLAY' | 'NEXT_PUBLIC_MARKETING_MENU_ENABLED' | 'NEXT_PUBLIC_STORAGE_BACKEND' | 'NEXT_PUBLIC_SUPABASE_URL' | 'NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY'>> {}
}


export type EnvSchemaAsStrings = {
  [Property in keyof CoercedEnvSchema]:
    CoercedEnvSchema[Property] extends string ? CoercedEnvSchema[Property]
      : (CoercedEnvSchema[Property] extends boolean ? ('true' | 'false') : string)
};

type _EnvSchemaAsStrings_0ed98659 = EnvSchemaAsStrings;
declare global {

  // add types for global import.meta.env
  interface ImportMetaEnv extends _EnvSchemaAsStrings_0ed98659 {}
  interface ImportMeta {
    readonly env: ImportMetaEnv;
  }

  // add types for global process.env
  namespace NodeJS {
    interface ProcessEnv extends _EnvSchemaAsStrings_0ed98659 {}
  }
}